### ISSUE TITLE
README

### ISSUE THREAD

**Issue by sirkitree** [j-hannah/js-report#5]
It would be good to have an explain in the README similar to what you told me today. Things I remember:
* how to build
* good project to try to learn various JS
  * which ones and where?
* put a link to the website
* maybe something about motives

As I get familiar with the current codebase I'll try to note some of this too.

**Comment by sirkitree** [comment]
Maybe this could double as the about page too on the website

**Comment by j-hannah** [comment]
👍 Thanks @sirkitree. I'll try to knock this out this weekend along with the load more functionality.

**Comment by j-hannah** [comment]
> seems this is not free, you paying for this

Yes, but I was already paying for it. Since this is not sanctioned, someone has to pay for now. I'm hoping we might get some sponsorship from Lullabot at some point.

> lib/config.js has an api key for youtube

Deleted it. Left over from first iteration.

> about page is currently blank

Added a sentence. 😄  I'd like to add an intro about what the site is about and then add contributor bios. Links back to Lullabot would probably go here as well.

> css is saved alongside of components

Yeah, I like this pattern a lot. I'm going to try to add Aphrodite tomorrow, though. After Carson's presentation last week, I think other devs would enjoy working with it.

> basic css variables in src/css

Yes, postcss.

> repository value in package.json needs update

Done. Thanks for catching that!
